import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`}>
                <header className='p-3 bg-slate-800 text-white text-lg font-bold'>Birdseye</header>
                <div className='bg-red-200 min-h-screen'>{children}</div>
                <footer className='p-2 bg-green-200'>Copyright: Galen Ciszek 2024</footer>
            </body>
        </html>
    );
}
